-- BlackShield Transportation reservation workflow
-- Run this file in the Supabase SQL Editor.

create table if not exists public.reservations (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.reservations
  add column if not exists reservation_id text,
  add column if not exists stripe_checkout_session_id text,
  add column if not exists stripe_payment_intent_id text,
  add column if not exists last_stripe_event_id text,
  add column if not exists customer_name text,
  add column if not exists customer_email text,
  add column if not exists customer_phone text,
  add column if not exists pickup_at timestamptz,
  add column if not exists pickup_local text,
  add column if not exists pickup_address text,
  add column if not exists dropoff_address text,
  add column if not exists vehicle_key text,
  add column if not exists vehicle_choice text,
  add column if not exists trip_type text,
  add column if not exists airport_zone text,
  add column if not exists requested_hours numeric,
  add column if not exists passenger_count integer,
  add column if not exists luggage_count integer,
  add column if not exists flight_number text,
  add column if not exists special_instructions text,
  add column if not exists payment_option text,
  add column if not exists currency text default 'usd',
  add column if not exists trip_total numeric(10,2),
  add column if not exists amount_paid numeric(10,2),
  add column if not exists remaining_balance numeric(10,2),
  add column if not exists payment_status text,
  add column if not exists reservation_status text default 'pending_confirmation',
  add column if not exists google_calendar_event_id text,
  add column if not exists owner_email_id text,
  add column if not exists owner_email_sent_at timestamptz,
  add column if not exists customer_email_id text,
  add column if not exists customer_email_sent_at timestamptz,
  add column if not exists workflow_status text default 'processing',
  add column if not exists workflow_error text,
  add column if not exists processed_at timestamptz;

create unique index if not exists reservations_reservation_id_key
  on public.reservations (reservation_id);

create unique index if not exists reservations_stripe_session_key
  on public.reservations (stripe_checkout_session_id);

create index if not exists reservations_pickup_at_idx
  on public.reservations (pickup_at);

create index if not exists reservations_status_idx
  on public.reservations (reservation_status, payment_status);

create or replace function public.set_reservations_updated_at()
returns trigger
language plpgsql
security invoker
set search_path = public
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists reservations_updated_at_trigger
  on public.reservations;

create trigger reservations_updated_at_trigger
before update on public.reservations
for each row
execute function public.set_reservations_updated_at();

alter table public.reservations enable row level security;

-- No public RLS policy is created. Only the private server-side
-- Supabase secret key performs reservation writes.

-- Permit the private server-side service role to manage reservations.
grant usage on schema public to service_role;

grant select, insert, update, delete
on table public.reservations
to service_role;

grant usage, select
on all sequences in schema public
to service_role;
